### ISSUE TITLE
Emulator running to fast - internal clock

### ISSUE THREAD

**Issue by pinballgithub** [markus-zzz/myc64-pocket#13]
I tried the Space Invaders rom to test to collision detection, which was not running properly before. Unfortuntely this rom is not running way to fast. Could you please check what has caused this behavior from 0.1 to 0.1.1?

**Comment by markus-zzz** [comment]
Ah, that was unfortunate. Could you provide the exact name / path of the `.prg`?

Probably something with collision interrupts being mistaken for raster line interrupts that is causing problems.

**Comment by pinballgithub** [comment]
Sure, the PRG is: Space Invaders (1982)(Commodore).prg from the crunched rom set.

**Comment by markus-zzz** [comment]
I cannot find that file in the recommended ROM set `OneLoad64-Games-Collection-v5.7z`. The closest I do see is
```
markus@workstation:~/Downloads/tmp/AlternativeFormats/PRGs/Crunched$ md5sum "Space Invaders (Mariano Kalafatovich - v1.1 - 2021).prg" 
ed4bb9a69446388cf7e3ee305bf8ae46  Space Invaders (Mariano Kalafatovich - v1.1 - 2021).prg
```
That seems playable but I cannot really tell if it is too fast or not as I generally suck at these games :)

Planet EMU does have a title with that name though
```
markus@workstation:~/Downloads$ md5sum "Space Invaders (1982)(Commodore).prg" 
7cdab90289139cfe46d2f1e495d2a316  Space Invaders (1982)(Commodore).prg
```
And I can confirm that one definitely plays way too fast.

Will have a look.

**Comment by pinballgithub** [comment]
Sorry, I got it from here. 

https://www.planetemu.net/rom/commodore-c64-games-prg/space-invaders-1982-commodore

**Comment by markus-zzz** [comment]
From what I can tell this game also runs way too fast with release `v0.1.0`. A quick look at the waveforms suggest that the game is not using raster interrupts so a bit unclear what controls the pacing.

**Comment by markus-zzz** [comment]
Appears to be resolved now. I have not examined exactly why but my guess is that it was when missing CIA Timer B was implemented in 
```
commit 58f3044a5facf0f6bf526a9676b422f959b4e345 (tag: v0.2.0)
```
