### ISSUE TITLE
QOL Request: Let cursor wrap around the edges of the OSD Keyboard

### ISSUE THREAD

**Issue by HeyItsLollie** [markus-zzz/myc64-pocket#15]
As a quality-of-life change, I'd like to see the cursor wrap the left and right edges of the keyboard, just to make it easier to reach keys on the opposite sides. Like so:

![myc64-osd-wraparound](https://github.com/markus-zzz/myc64-pocket/assets/30498581/f76c504b-0ac0-4c6d-8b4f-c284e397119b)

**Comment by HeyItsLollie** [comment]
> First, out of curiosity, did you generate that animation with the verilator bench? 😀

Just good ol' fashioned "take a few screenshots and make a mock-up in photoshop"!

> Maybe also vertical?

Vertical wrap is nice when it feels good, but not quite as necessary? There's only five rows to navigate vertically, compared to 15/16 keys horizontally. The spacebar is what makes vertical wrap kind of annoying for UX.

(Right now, as soon as the cursor moves to the spacebar, the cursor "forgets" where its position was in the previous row. You'd probably have to track the cursor's horizontal position in the background, "restore" it when navigating away from the spacebar, and then make sure that it doesn't cause issues for other rows, like the right-most keys.)

> Only problem with these things is that while some love it others may hate it and then I have ticket saying do the opposite.

😅 Yeah... Everyone gets used to how a feature currently works, and some people want to resist change more than others. Obviously I'm biased, I think this would be a pretty inoffensive feature, but worst-case scenario, it probably wouldn't be so bad to have a toggleable setting for "OSD Cursor can wraparound" in the core options.

**Comment by markus-zzz** [comment]
Yes, spacebar is the odd key that offsets everything. It is annoying even without wrap. 

Right now we keep track of the horizontal index and try to match that when moving verticaly. When we move to spacebar that index gets set to zero and when moving up we are still at zero.

Maybe remembering the index for the rows adjacent to spacebar (but not any other) is good.

I'll make a testbuild and upload to the issue in the next few days and then we take it from there.

**Comment by markus-zzz** [comment]
Experimental build with virtual keyboard wrap in both horizontal and vertical direction. The passage through space bar is handled as described above.

Does it work as you envisioned?

[MyC64-Pocket-test-keyb-wrap.zip](https://github.com/markus-zzz/myc64-pocket/files/15143335/MyC64-Pocket-test-keyb-wrap.zip)

**Comment by HeyItsLollie** [comment]
This is great, thank you for tackling this! Horizontal wrap is perfect, exactly what I envisioned. Vertical wrap is fairly easy to work with too, being able to move from the top row to spacebar instantly is more useful than I realized.

**Comment by markus-zzz** [comment]
Great! I agree this improves the user experience. I'll close the ticket once committed and released.
