### ISSUE TITLE
What version of one load should be used? 

### ISSUE THREAD

**Issue by Mika73** [markus-zzz/myc64-pocket#2]
Theres two versions of this collection. What version should be used with Analogue pocket? 

There are two files: OneLoadCollection5_Carousels.zip containing folders that you can unzip directly in the "PCUAE USB Drive://THEC64-CAROUSEL-GAMES/" folder in PCUAE. If you just like to run the games using the File loader without PCUAE you can download OneLoadCollection5_FileLoader.zip and unzip directly to a USB stick. The games have individual CJM files with the right joystick settings.

**Comment by markus-zzz** [comment]
OneLoad64-Games-Collection-v5.7z is the one I tried with. It is important to use the crunched .prg files.
