### ISSUE TITLE
[QoL] 2nd fire button

### ISSUE THREAD

**Issue by niknice** [markus-zzz/myc64-pocket#26]
Would it be possible to incorporate the 2nd fire button as used by many games. There is quite a lot of games that either officially or unofficially support this feature.

http://wiki.icomp.de/wiki/DB9-Joystick#C64

**Comment by markus-zzz** [comment]
I am still a bit confused with how the pocket maps the gamepad buttons - I understand it to be as follows (which is not the same way as a xbox controller afaict)
![gamepad drawio](https://github.com/user-attachments/assets/52bb9060-0c83-4109-a6bd-fdf9276a6795)

Have a look at commit 178c26acfbcb456cd with test build [MyC64-Pocket.zip](https://github.com/user-attachments/files/16522805/MyC64-Pocket.zip) and report back.

**Comment by markus-zzz** [comment]
Resolved as of release v0.2.6
