### ISSUE TITLE
C64 keyboard overlay graphics is garbled

### ISSUE THREAD

**Issue by janisc** [markus-zzz/myc64-pocket#28]
Steps to reproduce:
Press the select button to bring up the virtual keyboard

Expected results:
The keyboard overlay appears and is readable

Actual results:
The keyboard overlay is garbled, horizontal line strips.

**Comment by markus-zzz** [comment]
I think this is the bug that was fixed in d2de31994b7eee36f97a4612f58cc7e10a60ed87

In the meantime just use the sliders to set an osd offsets that is not zero.

**Comment by plastivore** [comment]
![c64_pocket-keyboard_glitch](https://github.com/user-attachments/assets/21b025a1-0a1a-4ee2-9877-585ec0a8c71c)

**Comment by markus-zzz** [comment]
Maybe I should create a new release with above mentioned fix.

**Comment by UScr00ge** [comment]
I would personally love a release with this fixed, but thanks for the offset workaround. That got me fixed!

**Comment by markus-zzz** [comment]
Finally got around to create a proper release 

https://github.com/markus-zzz/myc64-pocket/releases/tag/v0.2.7

Reason I have been dragging my feet is that when I use my release script to build a new release I get a new bitstream for the fpga and then I really should test that things still work.. That takes a lot of time.. Now I just patched the .json files in v0.2.6 manually.
