### ISSUE TITLE
[BUG] Issue #28 is unresolved

### ISSUE THREAD

**Issue by giacecco** [markus-zzz/myc64-pocket#30]
Same as described at https://github.com/markus-zzz/myc64-pocket/issues/28 despite using release 0.2.7 that is supposed to have resolved it. Thanks!

**Comment by markus-zzz** [comment]
First please verify contents of https://github.com/markus-zzz/myc64-pocket/blob/main/dist/Cores/markus-zzz.MyC64/interact.json on pocket SD

Then verify core.json

If both indicate that it is actually 0.2 7 then I guess it could be some settings cache lingering behind so a fresh reinstall of the core might help.

**Comment by giacecco** [comment]
Thanks for answering so quickly @markus-zzz . I am sorry but I had downloaded and installed the correct 0.2.7 version and, also after a fresh reinstall of the core, the issue is still there 🙁

`interact.json` actually does not refer to the version, but has the correct `defaultval` version set to 1 that I have seen in the workaround discussed [here](https://github.com/markus-zzz/myc64-pocket/commit/d2de31994b7eee36f97a4612f58cc7e10a60ed87).

What do you suggest I try next?

**Comment by markus-zzz** [comment]
Weird. Just moving both sliders away from zero should solve the issue.
That works for you right?

I cannot say why this manual intervention is needed though. It shouldn't be needed on a clean install unless some old setting is saved somewhere.

**Comment by markus-zzz** [comment]
My guess would be this

https://www.analogue.co/developer/docs/directories-and-sd-folder-structure

'Settings
Contains core and per-asset interact values that are persistent.'

**Comment by giacecco** [comment]
Thanks @markus-zzz , it's solved, it was probably like you said, thanks!
