### ISSUE TITLE
Moving the cursor around the keyboard is slow

### ISSUE THREAD

**Issue by dfilskov** [markus-zzz/myc64-pocket#5]
Thanks so much for all your effort bringing this beloved computer to the Pocket :) - much appreciated!

I've noticed that I can't simply press the D-pad to move the cursor around the keyboard to get to R, U, N, and RET. Most of my movements don't register. It seems there's a long delay after each action (D-pad or A button) - or the input is registered only 2-3 times per second and so misses perhaps 2 out of 3 actions.

Cheers!

**Comment by markus-zzz** [comment]
> Thanks so much for all your effort bringing this beloved computer to the Pocket :) - much appreciated!

Thanks!

> I've noticed that I can't simply press the D-pad to move the cursor around the keyboard to get to R, U, N, and RET. Most of my movements don't register. It seems there's a long delay after each action (D-pad or A button) - or the input is registered only 2-3 times per second and so misses perhaps 2 out of 3 actions.

Yes, the virtual keyboard is currently a bit clunky. Looking at https://github.com/markus-zzz/myc64-pocket/blob/main/src/bios/keyboard-virt.c it is implemented as an edge detector so the d-pad keys actually need to go from a depressed state to a a pressed state to be registered. On top of that the entire keyboard is redrawn between each read of the d-pad so it is indeed possible that keypresses are missed if you are too fast.

While simple to implement I realize this is really annoying. It is on my todo list of things to address next. I was thinking that some kind of auto repeat mechanism would be helpful for the d-pad when used in keyboard navigation. That and only doing partial redraw to get accurate input reads.

**Comment by dfilskov** [comment]
That makes sense :) - thanks!

Perhaps the whole thing could work without being drawn at all (key-checks ten times more often) and then just drawn e.g. 3 times a second (asynchrone with any key checks).

**Comment by markus-zzz** [comment]
I think it is time to setup interrupts in the housekeeping cpu. Then do something along the lines of what you suggest.

**Comment by dfilskov** [comment]
Sounds like me when I realized I had to learn IRQs on the C64 itself back in the day :) 


(I'm not a programmer but I did play with small machine code demos)

**Comment by markus-zzz** [comment]
I finally had a go at this. With the attached test build the input reading part is done in a 100Hz ISR while the OSD drawing takes place in the background. As far as I can tell this makes the user experience a lot snappier.

My original plan was to also setup some sort of auto repeat for the navigation keys in the menu and keyboard but after testing this I am not sure if that is still necessary.

[MyC64-Pocket-bios-irq-test.zip](https://github.com/markus-zzz/myc64-pocket/files/15044420/MyC64-Pocket-bios-irq-test.zip)

What do you think?

**Comment by markus-zzz** [comment]
Never mind, I found an easy way to do the auto repeat so it will go in as well in the next release :)

**Comment by dfilskov** [comment]
Cool! :)

**Comment by dfilskov** [comment]
Way better! :) - the keyboard graphics seem a little behind the movement but that's OK since it doesn't seem to miss any inputs now.

**Comment by markus-zzz** [comment]
I fixed the auto-repeat and sped up the redrawing so the graphics lagging should not be noticeable any more. I'll make a proper release of it either later today or sometime tomorrow.

**Comment by dfilskov** [comment]
Excellent!!

**Comment by markus-zzz** [comment]
Officially solved with https://github.com/markus-zzz/myc64-pocket/releases/tag/v0.1.2

**Comment by dfilskov** [comment]
Functions just perfectly now! - thanks a lot :)
