### ISSUE TITLE
OSD partly hidden with Integer+

### ISSUE THREAD

**Issue by dfilskov** [markus-zzz/myc64-pocket#6]
When you set Display size to Normal and Integer+ then part of the keyboard is outside the screen making it hard to use.

**Comment by dfilskov** [comment]
Way better! :) - the graphics seem a little behind the movement but that's OK. since it doesn't seem to mis any inputs now :)

**Comment by markus-zzz** [comment]
User [dukestah](https://github.com/dukestah) also commented on this issue in #17 (not sure if the ping works as github issues is rather limited)

So what should we do about this? The OSD can of course be moved anywhere on the screen and if we put it in the middle then this issue would go away but on the other hand it would block more vital parts making it hard to see what you type etc.

There is also the status bar that only makes sense to display in the upper/lower left/right corner. Definitely not in the middle.

I guess we could make the OSD offset configurable via the Analogue OS menu if that would make people happy. Any ideas?

**Comment by dfilskov** [comment]
Can you detect the visible area of the screen before drawing the keyboard?

**Comment by markus-zzz** [comment]
> Can you detect the visible area of the screen before drawing the keyboard?

Unfortunately I don't think that is possible.

We get notified with `OS Notify: Display Mode` when the display mode changes (see https://www.analogue.co/developer/docs/host-target-commands) but that only indicates CRT mode and says nothing about Integer+ scaling. I think it would be hard to use this information in some reliable way that wouldn't introduce new issues.

**Comment by dukestah** [comment]
> I guess we could make the OSD offset configurable via the Analogue OS menu if that would make people happy. Any ideas?

I think this is a pretty nice idea. When using the Dock I'm often using a real keyboard as well, so the OSD is used for Reset and/or disc state only, hence, I don't mind whether it would pop-up in the middle of the screen :)
The Integer+ mode is pretty useful to get a full-screen picture of the main area of the C64 but for some games/demos that use the border as well, it won't work very good. So positioning the OSD based on personal needs is probably the best option.

**Comment by dfilskov** [comment]
I see.

Perhaps it'd be OK to simply position the keyboard as close the edge of Integer+ as possible (perhaps slightly out view but not so that it obstructs the use) and let that be the default position for all display settings.

Also it could be 60% transparent perhaps.

**Comment by markus-zzz** [comment]
My plan right now is add **OSD x-offset** and **OSD y-offset** slider widgets to the **Core Settings** menu and then the end user can adjust the position of the OSD to his liking.

I have thought about the transparent thing a few times before but that is really a separate feature. The only way it would be sufficient to solve this one is if the OSD was always in the center of the screen but then that would not work well with the status bar.

**Comment by dfilskov** [comment]
Good point - offsets are fine!

**Comment by markus-zzz** [comment]
And finally a test build [MyC64-Pocket.zip](https://github.com/user-attachments/files/16568493/MyC64-Pocket.zip)

**Comment by markus-zzz** [comment]
Resolved as of release v0.2.6
