### ISSUE TITLE
Freeze after starting file

### ISSUE THREAD

**Issue by pinballgithub** [markus-zzz/myc64-pocket#8]
Alle files are starting, but as they require input via joystick I experience a freeze. Only reset or quitting the core helps.

**Comment by markus-zzz** [comment]
The pocket controller can be mapped to c64 joystick 1, joystick 2 or both in the rightmost menu tab.

Given that you have done that is there any specific .prg you are having problems with?

**Comment by pinballgithub** [comment]
Hi Markus, I tried some other roms: frogger freeze as well, Battle Chopper - works, Frenzy - works

It seems to depend on the rom, and unfortunately I selected some which were not functioning well.

**Comment by markus-zzz** [comment]
Yes, there are certainly `.prg` files that don't load up correctly or freeze/crash for some other reason with the current state of the core. I just setup a wiki page (editable by anyone) where we could keep track of what appears to be known good

https://github.com/markus-zzz/myc64-pocket/wiki/Working-PRGs

please feel free to add your findings there :)
